#include <bears/protocol/get_config.hpp>
#include <bears/protocol/config.hpp>
#include <bears/protocol/asset.hpp>
#include <bears/protocol/types.hpp>
#include <bears/protocol/version.hpp>

namespace bears { namespace protocol {

fc::variant_object get_config()
{
   fc::mutable_variant_object result;

#ifdef IS_TEST_NET
   result[ "IS_TEST_NET" ] = true;
   result["TESTNET_BLOCK_LIMIT"] = TESTNET_BLOCK_LIMIT;
#else
   result[ "IS_TEST_NET" ] = false;
#endif
#ifdef BEARS_ENABLE_SMT
   result[ "BEARS_ENABLE_SMT" ] = true;
   result["SMT_COINING_WITHDRAW_INTERVAL_SECONDS"] = SMT_COINING_WITHDRAW_INTERVAL_SECONDS;
   result["SMT_UPVOTE_LOCKOUT"] = SMT_UPVOTE_LOCKOUT;
   result["SMT_MAX_VOTABLE_ASSETS"] = SMT_MAX_VOTABLE_ASSETS;
#else
   result[ "BEARS_ENABLE_SMT" ] = false;
#endif

   result["BSD_SYMBOL"] = BSD_SYMBOL;
   result["BEARS_INITIAL_VOTE_POWER_RATE"] = BEARS_INITIAL_VOTE_POWER_RATE;
   result["BEARS_REDUCED_VOTE_POWER_RATE"] = BEARS_REDUCED_VOTE_POWER_RATE;
   result["BEARS_100_PERCENT"] = BEARS_100_PERCENT;
   result["BEARS_1_PERCENT"] = BEARS_1_PERCENT;
   result["BEARS_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD"] = BEARS_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD;
   result["BEARS_ACTIVE_CHALLENGE_COOLDOWN"] = BEARS_ACTIVE_CHALLENGE_COOLDOWN;
   result["BEARS_ACTIVE_CHALLENGE_FEE"] = BEARS_ACTIVE_CHALLENGE_FEE;
   result["BEARS_ADDRESS_PREFIX"] = BEARS_ADDRESS_PREFIX;
   result["BEARS_APR_PERCENT_MULTIPLY_PER_BLOCK"] = BEARS_APR_PERCENT_MULTIPLY_PER_BLOCK;
   result["BEARS_APR_PERCENT_MULTIPLY_PER_HOUR"] = BEARS_APR_PERCENT_MULTIPLY_PER_HOUR;
   result["BEARS_APR_PERCENT_MULTIPLY_PER_ROUND"] = BEARS_APR_PERCENT_MULTIPLY_PER_ROUND;
   result["BEARS_APR_PERCENT_SHIFT_PER_BLOCK"] = BEARS_APR_PERCENT_SHIFT_PER_BLOCK;
   result["BEARS_APR_PERCENT_SHIFT_PER_HOUR"] = BEARS_APR_PERCENT_SHIFT_PER_HOUR;
   result["BEARS_APR_PERCENT_SHIFT_PER_ROUND"] = BEARS_APR_PERCENT_SHIFT_PER_ROUND;
   result["BEARS_BANDWIDTH_AVERAGE_WINDOW_SECONDS"] = BEARS_BANDWIDTH_AVERAGE_WINDOW_SECONDS;
   result["BEARS_BANDWIDTH_PRECISION"] = BEARS_BANDWIDTH_PRECISION;
   result["BEARS_BLOCKCHAIN_PRECISION"] = BEARS_BLOCKCHAIN_PRECISION;
   result["BEARS_BLOCKCHAIN_PRECISION_DIGITS"] = BEARS_BLOCKCHAIN_PRECISION_DIGITS;
   result["BEARS_BLOCKCHAIN_HARDFORK_VERSION"] = BEARS_BLOCKCHAIN_HARDFORK_VERSION;
   result["BEARS_BLOCKCHAIN_VERSION"] = BEARS_BLOCKCHAIN_VERSION;
   result["BEARS_BLOCK_INTERVAL"] = BEARS_BLOCK_INTERVAL;
   result["BEARS_BLOCKS_PER_DAY"] = BEARS_BLOCKS_PER_DAY;
   result["BEARS_BLOCKS_PER_HOUR"] = BEARS_BLOCKS_PER_HOUR;
   result["BEARS_BLOCKS_PER_YEAR"] = BEARS_BLOCKS_PER_YEAR;
   result["BEARS_CASHOUT_WINDOW_SECONDS"] = BEARS_CASHOUT_WINDOW_SECONDS;
   result["BEARS_CASHOUT_WINDOW_SECONDS_PRE_HF12"] = BEARS_CASHOUT_WINDOW_SECONDS_PRE_HF12;
   result["BEARS_CASHOUT_WINDOW_SECONDS_PRE_HF17"] = BEARS_CASHOUT_WINDOW_SECONDS_PRE_HF17;
   result["BEARS_CHAIN_ID"] = BEARS_CHAIN_ID;
   result["BEARS_COMMENT_REWARD_FUND_NAME"] = BEARS_COMMENT_REWARD_FUND_NAME;
   result["BEARS_CONTENT_APR_PERCENT"] = BEARS_CONTENT_APR_PERCENT;
   result["BEARS_CONTENT_CONSTANT_HF0"] = BEARS_CONTENT_CONSTANT_HF0;
   result["BEARS_CONTENT_REWARD_PERCENT"] = BEARS_CONTENT_REWARD_PERCENT;
   result["BEARS_CONVERSION_DELAY"] = BEARS_CONVERSION_DELAY;
   result["BEARS_CONVERSION_DELAY_PRE_HF_16"] = BEARS_CONVERSION_DELAY_PRE_HF_16;
   result["BEARS_CREATE_ACCOUNT_DELEGATION_RATIO"] = BEARS_CREATE_ACCOUNT_DELEGATION_RATIO;
   result["BEARS_CREATE_ACCOUNT_DELEGATION_TIME"] = BEARS_CREATE_ACCOUNT_DELEGATION_TIME;
   result["BEARS_CREATE_ACCOUNT_WITH_BEARS_MODIFIER"] = BEARS_CREATE_ACCOUNT_WITH_BEARS_MODIFIER;
   result["BEARS_CURATE_APR_PERCENT"] = BEARS_CURATE_APR_PERCENT;
   result["BEARS_DEFAULT_BSD_INTEREST_RATE"] = BEARS_DEFAULT_BSD_INTEREST_RATE;
   result["BEARS_EQUIHASH_K"] = BEARS_EQUIHASH_K;
   result["BEARS_EQUIHASH_N"] = BEARS_EQUIHASH_N;
   result["BEARS_FEED_HISTORY_WINDOW"] = BEARS_FEED_HISTORY_WINDOW;
   result["BEARS_FEED_HISTORY_WINDOW_PRE_HF_16"] = BEARS_FEED_HISTORY_WINDOW_PRE_HF_16;
   result["BEARS_FEED_INTERVAL_BLOCKS"] = BEARS_FEED_INTERVAL_BLOCKS;
   result["BEARS_GENESIS_TIME"] = BEARS_GENESIS_TIME;
   result["BEARS_HARDFORK_REQUIRED_WITNESSES"] = BEARS_HARDFORK_REQUIRED_WITNESSES;
   result["BEARS_INFLATION_NARROWING_PERIOD"] = BEARS_INFLATION_NARROWING_PERIOD;
   result["BEARS_INFLATION_RATE_START_PERCENT"] = BEARS_INFLATION_RATE_START_PERCENT;
   result["BEARS_INFLATION_RATE_STOP_PERCENT"] = BEARS_INFLATION_RATE_STOP_PERCENT;
   result["BEARS_INIT_MINER_NAME"] = BEARS_INIT_MINER_NAME;
   result["BEARS_INIT_PUBLIC_KEY_STR"] = BEARS_INIT_PUBLIC_KEY_STR;
#if 0
   // do not expose private key, period.
   // we need this line present but inactivated so CI check for all constants in config.hpp doesn't complain.
   result["BEARS_INIT_PRIVATE_KEY"] = BEARS_INIT_PRIVATE_KEY;
#endif
   result["BEARS_INIT_SUPPLY"] = BEARS_INIT_SUPPLY;
   result["BEARS_INIT_TIME"] = BEARS_INIT_TIME;
   result["BEARS_IRREVERSIBLE_THRESHOLD"] = BEARS_IRREVERSIBLE_THRESHOLD;
   result["BEARS_LIQUIDITY_APR_PERCENT"] = BEARS_LIQUIDITY_APR_PERCENT;
   result["BEARS_LIQUIDITY_REWARD_BLOCKS"] = BEARS_LIQUIDITY_REWARD_BLOCKS;
   result["BEARS_LIQUIDITY_REWARD_PERIOD_SEC"] = BEARS_LIQUIDITY_REWARD_PERIOD_SEC;
   result["BEARS_LIQUIDITY_TIMEOUT_SEC"] = BEARS_LIQUIDITY_TIMEOUT_SEC;
   result["BEARS_MAX_ACCOUNT_CREATION_FEE"] = BEARS_MAX_ACCOUNT_CREATION_FEE;
   result["BEARS_MAX_ACCOUNT_NAME_LENGTH"] = BEARS_MAX_ACCOUNT_NAME_LENGTH;
   result["BEARS_MAX_ACCOUNT_WITNESS_VOTES"] = BEARS_MAX_ACCOUNT_WITNESS_VOTES;
   result["BEARS_MAX_ASSET_WHITELIST_AUTHORITIES"] = BEARS_MAX_ASSET_WHITELIST_AUTHORITIES;
   result["BEARS_MAX_AUTHORITY_MEMBERSHIP"] = BEARS_MAX_AUTHORITY_MEMBERSHIP;
   result["BEARS_MAX_BLOCK_SIZE"] = BEARS_MAX_BLOCK_SIZE;
   result["BEARS_SOFT_MAX_BLOCK_SIZE"] = BEARS_SOFT_MAX_BLOCK_SIZE;
   result["BEARS_MAX_CASHOUT_WINDOW_SECONDS"] = BEARS_MAX_CASHOUT_WINDOW_SECONDS;
   result["BEARS_MAX_COMMENT_DEPTH"] = BEARS_MAX_COMMENT_DEPTH;
   result["BEARS_MAX_COMMENT_DEPTH_PRE_HF17"] = BEARS_MAX_COMMENT_DEPTH_PRE_HF17;
   result["BEARS_MAX_FEED_AGE_SECONDS"] = BEARS_MAX_FEED_AGE_SECONDS;
   result["BEARS_MAX_INSTANCE_ID"] = BEARS_MAX_INSTANCE_ID;
   result["BEARS_MAX_MEMO_SIZE"] = BEARS_MAX_MEMO_SIZE;
   result["BEARS_MAX_WITNESSES"] = BEARS_MAX_WITNESSES;
   result["BEARS_MAX_MINER_WITNESSES_HF0"] = BEARS_MAX_MINER_WITNESSES_HF0;
   result["BEARS_MAX_MINER_WITNESSES_HF17"] = BEARS_MAX_MINER_WITNESSES_HF17;
   result["BEARS_MAX_PERMLINK_LENGTH"] = BEARS_MAX_PERMLINK_LENGTH;
   result["BEARS_MAX_PROXY_RECURSION_DEPTH"] = BEARS_MAX_PROXY_RECURSION_DEPTH;
   result["BEARS_MAX_RATION_DECAY_RATE"] = BEARS_MAX_RATION_DECAY_RATE;
   result["BEARS_MAX_RESERVE_RATIO"] = BEARS_MAX_RESERVE_RATIO;
   result["BEARS_MAX_RUNNER_WITNESSES_HF0"] = BEARS_MAX_RUNNER_WITNESSES_HF0;
   result["BEARS_MAX_RUNNER_WITNESSES_HF17"] = BEARS_MAX_RUNNER_WITNESSES_HF17;
   result["BEARS_MAX_SATOSHIS"] = BEARS_MAX_SATOSHIS;
   result["BEARS_MAX_SHARE_SUPPLY"] = BEARS_MAX_SHARE_SUPPLY;
   result["BEARS_MAX_SIG_CHECK_DEPTH"] = BEARS_MAX_SIG_CHECK_DEPTH;
   result["BEARS_MAX_SIG_CHECK_ACCOUNTS"] = BEARS_MAX_SIG_CHECK_ACCOUNTS;
   result["BEARS_MAX_TIME_UNTIL_EXPIRATION"] = BEARS_MAX_TIME_UNTIL_EXPIRATION;
   result["BEARS_MAX_TRANSACTION_SIZE"] = BEARS_MAX_TRANSACTION_SIZE;
   result["BEARS_MAX_UNDO_HISTORY"] = BEARS_MAX_UNDO_HISTORY;
   result["BEARS_MAX_URL_LENGTH"] = BEARS_MAX_URL_LENGTH;
   result["BEARS_MAX_VOTE_CHANGES"] = BEARS_MAX_VOTE_CHANGES;
   result["BEARS_MAX_VOTED_WITNESSES_HF0"] = BEARS_MAX_VOTED_WITNESSES_HF0;
   result["BEARS_MAX_VOTED_WITNESSES_HF17"] = BEARS_MAX_VOTED_WITNESSES_HF17;
   result["BEARS_MAX_WITHDRAW_ROUTES"] = BEARS_MAX_WITHDRAW_ROUTES;
   result["BEARS_MAX_WITNESS_URL_LENGTH"] = BEARS_MAX_WITNESS_URL_LENGTH;
   result["BEARS_MIN_ACCOUNT_CREATION_FEE"] = BEARS_MIN_ACCOUNT_CREATION_FEE;
   result["BEARS_MIN_ACCOUNT_NAME_LENGTH"] = BEARS_MIN_ACCOUNT_NAME_LENGTH;
   result["BEARS_MIN_BLOCK_SIZE_LIMIT"] = BEARS_MIN_BLOCK_SIZE_LIMIT;
   result["BEARS_MIN_BLOCK_SIZE"] = BEARS_MIN_BLOCK_SIZE;
   result["BEARS_MIN_CONTENT_REWARD"] = BEARS_MIN_CONTENT_REWARD;
   result["BEARS_MIN_CURATE_REWARD"] = BEARS_MIN_CURATE_REWARD;
   result["BEARS_MIN_PERMLINK_LENGTH"] = BEARS_MIN_PERMLINK_LENGTH;
   result["BEARS_MIN_REPLY_INTERVAL"] = BEARS_MIN_REPLY_INTERVAL;
   result["BEARS_MIN_REPLY_INTERVAL_HF20"] = BEARS_MIN_REPLY_INTERVAL_HF20;
   result["BEARS_MIN_ROOT_COMMENT_INTERVAL"] = BEARS_MIN_ROOT_COMMENT_INTERVAL;
   result["BEARS_MIN_VOTE_INTERVAL_SEC"] = BEARS_MIN_VOTE_INTERVAL_SEC;
   result["BEARS_MINER_ACCOUNT"] = BEARS_MINER_ACCOUNT;
   result["BEARS_MINER_PAY_PERCENT"] = BEARS_MINER_PAY_PERCENT;
   result["BEARS_MIN_FEEDS"] = BEARS_MIN_FEEDS;
   result["BEARS_MINING_REWARD"] = BEARS_MINING_REWARD;
   result["BEARS_MINING_TIME"] = BEARS_MINING_TIME;
   result["BEARS_MIN_LIQUIDITY_REWARD"] = BEARS_MIN_LIQUIDITY_REWARD;
   result["BEARS_MIN_LIQUIDITY_REWARD_PERIOD_SEC"] = BEARS_MIN_LIQUIDITY_REWARD_PERIOD_SEC;
   result["BEARS_MIN_PAYOUT_BSD"] = BEARS_MIN_PAYOUT_BSD;
   result["BEARS_MIN_POW_REWARD"] = BEARS_MIN_POW_REWARD;
   result["BEARS_MIN_PRODUCER_REWARD"] = BEARS_MIN_PRODUCER_REWARD;
   result["BEARS_MIN_TRANSACTION_EXPIRATION_LIMIT"] = BEARS_MIN_TRANSACTION_EXPIRATION_LIMIT;
   result["BEARS_MIN_TRANSACTION_SIZE_LIMIT"] = BEARS_MIN_TRANSACTION_SIZE_LIMIT;
   result["BEARS_MIN_UNDO_HISTORY"] = BEARS_MIN_UNDO_HISTORY;
   result["BEARS_NULL_ACCOUNT"] = BEARS_NULL_ACCOUNT;
   result["BEARS_NUM_INIT_MINERS"] = BEARS_NUM_INIT_MINERS;
   result["BEARS_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM"] = BEARS_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM;
   result["BEARS_OWNER_AUTH_RECOVERY_PERIOD"] = BEARS_OWNER_AUTH_RECOVERY_PERIOD;
   result["BEARS_OWNER_CHALLENGE_COOLDOWN"] = BEARS_OWNER_CHALLENGE_COOLDOWN;
   result["BEARS_OWNER_CHALLENGE_FEE"] = BEARS_OWNER_CHALLENGE_FEE;
   result["BEARS_OWNER_UPDATE_LIMIT"] = BEARS_OWNER_UPDATE_LIMIT;
   result["BEARS_POST_AVERAGE_WINDOW"] = BEARS_POST_AVERAGE_WINDOW;
   result["BEARS_POST_REWARD_FUND_NAME"] = BEARS_POST_REWARD_FUND_NAME;
   result["BEARS_POST_WEIGHT_CONSTANT"] = BEARS_POST_WEIGHT_CONSTANT;
   result["BEARS_POW_APR_PERCENT"] = BEARS_POW_APR_PERCENT;
   result["BEARS_PRODUCER_APR_PERCENT"] = BEARS_PRODUCER_APR_PERCENT;
   result["BEARS_PROXY_TO_SELF_ACCOUNT"] = BEARS_PROXY_TO_SELF_ACCOUNT;
   result["BEARS_BSD_INTEREST_COMPOUND_INTERVAL_SEC"] = BEARS_BSD_INTEREST_COMPOUND_INTERVAL_SEC;
   result["BEARS_SECONDS_PER_YEAR"] = BEARS_SECONDS_PER_YEAR;
   result["BEARS_RECENT_RSHARES_DECAY_TIME_HF19"] = BEARS_RECENT_RSHARES_DECAY_TIME_HF19;
   result["BEARS_RECENT_RSHARES_DECAY_TIME_HF17"] = BEARS_RECENT_RSHARES_DECAY_TIME_HF17;
   result["BEARS_REVERSE_AUCTION_WINDOW_SECONDS_HF6"] = BEARS_REVERSE_AUCTION_WINDOW_SECONDS_HF6;
   result["BEARS_REVERSE_AUCTION_WINDOW_SECONDS_HF20"] = BEARS_REVERSE_AUCTION_WINDOW_SECONDS_HF20;
   result["BEARS_ROOT_POST_PARENT"] = BEARS_ROOT_POST_PARENT;
   result["BEARS_SAVINGS_WITHDRAW_REQUEST_LIMIT"] = BEARS_SAVINGS_WITHDRAW_REQUEST_LIMIT;
   result["BEARS_SAVINGS_WITHDRAW_TIME"] = BEARS_SAVINGS_WITHDRAW_TIME;
   result["BEARS_BSD_START_PERCENT_HF14"] = BEARS_BSD_START_PERCENT_HF14;
   result["BEARS_BSD_START_PERCENT_HF20"] = BEARS_BSD_START_PERCENT_HF20;
   result["BEARS_BSD_STOP_PERCENT_HF14"] = BEARS_BSD_STOP_PERCENT_HF14;
   result["BEARS_BSD_STOP_PERCENT_HF20"] = BEARS_BSD_STOP_PERCENT_HF20;
   result["BEARS_SECOND_CASHOUT_WINDOW"] = BEARS_SECOND_CASHOUT_WINDOW;
   result["BEARS_SOFT_MAX_COMMENT_DEPTH"] = BEARS_SOFT_MAX_COMMENT_DEPTH;
   result["BEARS_START_MINER_VOTING_BLOCK"] = BEARS_START_MINER_VOTING_BLOCK;
   result["BEARS_START_COINING_BLOCK"] = BEARS_START_COINING_BLOCK;
   result["BEARS_TEMP_ACCOUNT"] = BEARS_TEMP_ACCOUNT;
   result["BEARS_UPVOTE_LOCKOUT_HF7"] = BEARS_UPVOTE_LOCKOUT_HF7;
   result["BEARS_UPVOTE_LOCKOUT_HF17"] = BEARS_UPVOTE_LOCKOUT_HF17;
   result["BEARS_UPVOTE_LOCKOUT_SECONDS"] = BEARS_UPVOTE_LOCKOUT_SECONDS;
   result["BEARS_COINING_FUND_PERCENT"] = BEARS_COINING_FUND_PERCENT;
   result["BEARS_COINING_WITHDRAW_INTERVALS"] = BEARS_COINING_WITHDRAW_INTERVALS;
   result["BEARS_COINING_WITHDRAW_INTERVALS_PRE_HF_16"] = BEARS_COINING_WITHDRAW_INTERVALS_PRE_HF_16;
   result["BEARS_COINING_WITHDRAW_INTERVAL_SECONDS"] = BEARS_COINING_WITHDRAW_INTERVAL_SECONDS;
   result["BEARS_VOTE_DUST_THRESHOLD"] = BEARS_VOTE_DUST_THRESHOLD;
   result["BEARS_VOTING_MANA_REGENERATION_SECONDS"] = BEARS_VOTING_MANA_REGENERATION_SECONDS;
   result["BEARS_SYMBOL"] = BEARS_SYMBOL;
   result["COINS_SYMBOL"] = COINS_SYMBOL;
   result["BEARS_VIRTUAL_SCHEDULE_LAP_LENGTH"] = BEARS_VIRTUAL_SCHEDULE_LAP_LENGTH;
   result["BEARS_VIRTUAL_SCHEDULE_LAP_LENGTH2"] = BEARS_VIRTUAL_SCHEDULE_LAP_LENGTH2;
   result["BEARS_MAX_LIMIT_ORDER_EXPIRATION"] = BEARS_MAX_LIMIT_ORDER_EXPIRATION;
   result["BEARS_DELEGATION_RETURN_PERIOD_HF0"] = BEARS_DELEGATION_RETURN_PERIOD_HF0;
   result["BEARS_DELEGATION_RETURN_PERIOD_HF20"] = BEARS_DELEGATION_RETURN_PERIOD_HF20;
   result["BEARS_RD_MIN_DECAY_BITS"] = BEARS_RD_MIN_DECAY_BITS;
   result["BEARS_RD_MAX_DECAY_BITS"] = BEARS_RD_MAX_DECAY_BITS;
   result["BEARS_RD_DECAY_DENOM_SHIFT"] = BEARS_RD_DECAY_DENOM_SHIFT;
   result["BEARS_RD_MAX_POOL_BITS"] = BEARS_RD_MAX_POOL_BITS;
   result["BEARS_RD_MAX_BUDGET_1"] = BEARS_RD_MAX_BUDGET_1;
   result["BEARS_RD_MAX_BUDGET_2"] = BEARS_RD_MAX_BUDGET_2;
   result["BEARS_RD_MAX_BUDGET_3"] = BEARS_RD_MAX_BUDGET_3;
   result["BEARS_RD_MAX_BUDGET"] = BEARS_RD_MAX_BUDGET;
   result["BEARS_RD_MIN_DECAY"] = BEARS_RD_MIN_DECAY;
   result["BEARS_RD_MIN_BUDGET"] = BEARS_RD_MIN_BUDGET;
   result["BEARS_RD_MAX_DECAY"] = BEARS_RD_MAX_DECAY;
   result["BEARS_ACCOUNT_SUBSIDY_PRECISION"] = BEARS_ACCOUNT_SUBSIDY_PRECISION;
   result["BEARS_WITNESS_SUBSIDY_BUDGET_PERCENT"] = BEARS_WITNESS_SUBSIDY_BUDGET_PERCENT;
   result["BEARS_WITNESS_SUBSIDY_DECAY_PERCENT"] = BEARS_WITNESS_SUBSIDY_DECAY_PERCENT;
   result["BEARS_DEFAULT_ACCOUNT_SUBSIDY_DECAY"] = BEARS_DEFAULT_ACCOUNT_SUBSIDY_DECAY;
   result["BEARS_DEFAULT_ACCOUNT_SUBSIDY_BUDGET"] = BEARS_DEFAULT_ACCOUNT_SUBSIDY_BUDGET;
   result["BEARS_DECAY_BACKSTOP_PERCENT"] = BEARS_DECAY_BACKSTOP_PERCENT;

   return result;
}

} } // bears::protocol
