#include <voilk/protocol/get_config.hpp>
#include <voilk/protocol/config.hpp>
#include <voilk/protocol/asset.hpp>
#include <voilk/protocol/types.hpp>
#include <voilk/protocol/version.hpp>

namespace voilk { namespace protocol {

fc::variant_object get_config()
{
   fc::mutable_variant_object result;

#ifdef IS_TEST_NET
   result[ "IS_TEST_NET" ] = true;
   result["TESTNET_BLOCK_LIMIT"] = TESTNET_BLOCK_LIMIT;
#else
   result[ "IS_TEST_NET" ] = false;
#endif
#ifdef VOILK_ENABLE_SMT
   result[ "VOILK_ENABLE_SMT" ] = true;
   result["SMT_COINING_WITHDRAW_INTERVAL_SECONDS"] = SMT_COINING_WITHDRAW_INTERVAL_SECONDS;
   result["SMT_UPVOTE_LOCKOUT"] = SMT_UPVOTE_LOCKOUT;
   result["SMT_MAX_VOTABLE_ASSETS"] = SMT_MAX_VOTABLE_ASSETS;
#else
   result[ "VOILK_ENABLE_SMT" ] = false;
#endif

   result["VSD_SYMBOL"] = VSD_SYMBOL;
   result["VOILK_INITIAL_VOTE_POWER_RATE"] = VOILK_INITIAL_VOTE_POWER_RATE;
   result["VOILK_REDUCED_VOTE_POWER_RATE"] = VOILK_REDUCED_VOTE_POWER_RATE;
   result["VOILK_100_PERCENT"] = VOILK_100_PERCENT;
   result["VOILK_1_PERCENT"] = VOILK_1_PERCENT;
   result["VOILK_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD"] = VOILK_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD;
   result["VOILK_ACTIVE_CHALLENGE_COOLDOWN"] = VOILK_ACTIVE_CHALLENGE_COOLDOWN;
   result["VOILK_ACTIVE_CHALLENGE_FEE"] = VOILK_ACTIVE_CHALLENGE_FEE;
   result["VOILK_ADDRESS_PREFIX"] = VOILK_ADDRESS_PREFIX;
   result["VOILK_APR_PERCENT_MULTIPLY_PER_BLOCK"] = VOILK_APR_PERCENT_MULTIPLY_PER_BLOCK;
   result["VOILK_APR_PERCENT_MULTIPLY_PER_HOUR"] = VOILK_APR_PERCENT_MULTIPLY_PER_HOUR;
   result["VOILK_APR_PERCENT_MULTIPLY_PER_ROUND"] = VOILK_APR_PERCENT_MULTIPLY_PER_ROUND;
   result["VOILK_APR_PERCENT_SHIFT_PER_BLOCK"] = VOILK_APR_PERCENT_SHIFT_PER_BLOCK;
   result["VOILK_APR_PERCENT_SHIFT_PER_HOUR"] = VOILK_APR_PERCENT_SHIFT_PER_HOUR;
   result["VOILK_APR_PERCENT_SHIFT_PER_ROUND"] = VOILK_APR_PERCENT_SHIFT_PER_ROUND;
   result["VOILK_BANDWIDTH_AVERAGE_WINDOW_SECONDS"] = VOILK_BANDWIDTH_AVERAGE_WINDOW_SECONDS;
   result["VOILK_BANDWIDTH_PRECISION"] = VOILK_BANDWIDTH_PRECISION;
   result["VOILK_BLOCKCHAIN_PRECISION"] = VOILK_BLOCKCHAIN_PRECISION;
   result["VOILK_BLOCKCHAIN_PRECISION_DIGITS"] = VOILK_BLOCKCHAIN_PRECISION_DIGITS;
   result["VOILK_BLOCKCHAIN_HARDFORK_VERSION"] = VOILK_BLOCKCHAIN_HARDFORK_VERSION;
   result["VOILK_BLOCKCHAIN_VERSION"] = VOILK_BLOCKCHAIN_VERSION;
   result["VOILK_BLOCK_INTERVAL"] = VOILK_BLOCK_INTERVAL;
   result["VOILK_BLOCKS_PER_DAY"] = VOILK_BLOCKS_PER_DAY;
   result["VOILK_BLOCKS_PER_HOUR"] = VOILK_BLOCKS_PER_HOUR;
   result["VOILK_BLOCKS_PER_YEAR"] = VOILK_BLOCKS_PER_YEAR;
   result["VOILK_CASHOUT_WINDOW_SECONDS"] = VOILK_CASHOUT_WINDOW_SECONDS;
   result["VOILK_CASHOUT_WINDOW_SECONDS_PRE_HF12"] = VOILK_CASHOUT_WINDOW_SECONDS_PRE_HF12;
   result["VOILK_CASHOUT_WINDOW_SECONDS_PRE_HF17"] = VOILK_CASHOUT_WINDOW_SECONDS_PRE_HF17;
   result["VOILK_CHAIN_ID"] = VOILK_CHAIN_ID;
   result["VOILK_COMMENT_REWARD_FUND_NAME"] = VOILK_COMMENT_REWARD_FUND_NAME;
   result["VOILK_CONTENT_APR_PERCENT"] = VOILK_CONTENT_APR_PERCENT;
   result["VOILK_CONTENT_CONSTANT_HF0"] = VOILK_CONTENT_CONSTANT_HF0;
   result["VOILK_CONTENT_REWARD_PERCENT"] = VOILK_CONTENT_REWARD_PERCENT;
   result["VOILK_CONVERSION_DELAY"] = VOILK_CONVERSION_DELAY;
   result["VOILK_CONVERSION_DELAY_PRE_HF_16"] = VOILK_CONVERSION_DELAY_PRE_HF_16;
   result["VOILK_CREATE_ACCOUNT_DELEGATION_RATIO"] = VOILK_CREATE_ACCOUNT_DELEGATION_RATIO;
   result["VOILK_CREATE_ACCOUNT_DELEGATION_TIME"] = VOILK_CREATE_ACCOUNT_DELEGATION_TIME;
   result["VOILK_CREATE_ACCOUNT_WITH_VOILK_MODIFIER"] = VOILK_CREATE_ACCOUNT_WITH_VOILK_MODIFIER;
   result["VOILK_CURATE_APR_PERCENT"] = VOILK_CURATE_APR_PERCENT;
   result["VOILK_DEFAULT_VSD_INTEREST_RATE"] = VOILK_DEFAULT_VSD_INTEREST_RATE;
   result["VOILK_EQUIHASH_K"] = VOILK_EQUIHASH_K;
   result["VOILK_EQUIHASH_N"] = VOILK_EQUIHASH_N;
   result["VOILK_FEED_HISTORY_WINDOW"] = VOILK_FEED_HISTORY_WINDOW;
   result["VOILK_FEED_HISTORY_WINDOW_PRE_HF_16"] = VOILK_FEED_HISTORY_WINDOW_PRE_HF_16;
   result["VOILK_FEED_INTERVAL_BLOCKS"] = VOILK_FEED_INTERVAL_BLOCKS;
   result["VOILK_GENESIS_TIME"] = VOILK_GENESIS_TIME;
   result["VOILK_HARDFORK_REQUIRED_WITNESSES"] = VOILK_HARDFORK_REQUIRED_WITNESSES;
   result["VOILK_INFLATION_NARROWING_PERIOD"] = VOILK_INFLATION_NARROWING_PERIOD;
   result["VOILK_INFLATION_RATE_START_PERCENT"] = VOILK_INFLATION_RATE_START_PERCENT;
   result["VOILK_INFLATION_RATE_STOP_PERCENT"] = VOILK_INFLATION_RATE_STOP_PERCENT;
   result["VOILK_INIT_MINER_NAME"] = VOILK_INIT_MINER_NAME;
   result["VOILK_INIT_PUBLIC_KEY_STR"] = VOILK_INIT_PUBLIC_KEY_STR;
#if 0
   // do not expose private key, period.
   // we need this line present but inactivated so CI check for all constants in config.hpp doesn't complain.
   result["VOILK_INIT_PRIVATE_KEY"] = VOILK_INIT_PRIVATE_KEY;
#endif
   result["VOILK_INIT_SUPPLY"] = VOILK_INIT_SUPPLY;
   result["VOILK_INIT_TIME"] = VOILK_INIT_TIME;
   result["VOILK_IRREVERSIBLE_THRESHOLD"] = VOILK_IRREVERSIBLE_THRESHOLD;
   result["VOILK_LIQUIDITY_APR_PERCENT"] = VOILK_LIQUIDITY_APR_PERCENT;
   result["VOILK_LIQUIDITY_REWARD_BLOCKS"] = VOILK_LIQUIDITY_REWARD_BLOCKS;
   result["VOILK_LIQUIDITY_REWARD_PERIOD_SEC"] = VOILK_LIQUIDITY_REWARD_PERIOD_SEC;
   result["VOILK_LIQUIDITY_TIMEOUT_SEC"] = VOILK_LIQUIDITY_TIMEOUT_SEC;
   result["VOILK_MAX_ACCOUNT_CREATION_FEE"] = VOILK_MAX_ACCOUNT_CREATION_FEE;
   result["VOILK_MAX_ACCOUNT_NAME_LENGTH"] = VOILK_MAX_ACCOUNT_NAME_LENGTH;
   result["VOILK_MAX_ACCOUNT_WITNESS_VOTES"] = VOILK_MAX_ACCOUNT_WITNESS_VOTES;
   result["VOILK_MAX_ASSET_WHITELIST_AUTHORITIES"] = VOILK_MAX_ASSET_WHITELIST_AUTHORITIES;
   result["VOILK_MAX_AUTHORITY_MEMBERSHIP"] = VOILK_MAX_AUTHORITY_MEMBERSHIP;
   result["VOILK_MAX_BLOCK_SIZE"] = VOILK_MAX_BLOCK_SIZE;
   result["VOILK_SOFT_MAX_BLOCK_SIZE"] = VOILK_SOFT_MAX_BLOCK_SIZE;
   result["VOILK_MAX_CASHOUT_WINDOW_SECONDS"] = VOILK_MAX_CASHOUT_WINDOW_SECONDS;
   result["VOILK_MAX_COMMENT_DEPTH"] = VOILK_MAX_COMMENT_DEPTH;
   result["VOILK_MAX_COMMENT_DEPTH_PRE_HF17"] = VOILK_MAX_COMMENT_DEPTH_PRE_HF17;
   result["VOILK_MAX_FEED_AGE_SECONDS"] = VOILK_MAX_FEED_AGE_SECONDS;
   result["VOILK_MAX_INSTANCE_ID"] = VOILK_MAX_INSTANCE_ID;
   result["VOILK_MAX_MEMO_SIZE"] = VOILK_MAX_MEMO_SIZE;
   result["VOILK_MAX_WITNESSES"] = VOILK_MAX_WITNESSES;
   result["VOILK_MAX_MINER_WITNESSES_HF0"] = VOILK_MAX_MINER_WITNESSES_HF0;
   result["VOILK_MAX_MINER_WITNESSES_HF17"] = VOILK_MAX_MINER_WITNESSES_HF17;
   result["VOILK_MAX_PERMLINK_LENGTH"] = VOILK_MAX_PERMLINK_LENGTH;
   result["VOILK_MAX_PROXY_RECURSION_DEPTH"] = VOILK_MAX_PROXY_RECURSION_DEPTH;
   result["VOILK_MAX_RATION_DECAY_RATE"] = VOILK_MAX_RATION_DECAY_RATE;
   result["VOILK_MAX_RESERVE_RATIO"] = VOILK_MAX_RESERVE_RATIO;
   result["VOILK_MAX_RUNNER_WITNESSES_HF0"] = VOILK_MAX_RUNNER_WITNESSES_HF0;
   result["VOILK_MAX_RUNNER_WITNESSES_HF17"] = VOILK_MAX_RUNNER_WITNESSES_HF17;
   result["VOILK_MAX_SATOSHIS"] = VOILK_MAX_SATOSHIS;
   result["VOILK_MAX_SHARE_SUPPLY"] = VOILK_MAX_SHARE_SUPPLY;
   result["VOILK_MAX_SIG_CHECK_DEPTH"] = VOILK_MAX_SIG_CHECK_DEPTH;
   result["VOILK_MAX_SIG_CHECK_ACCOUNTS"] = VOILK_MAX_SIG_CHECK_ACCOUNTS;
   result["VOILK_MAX_TIME_UNTIL_EXPIRATION"] = VOILK_MAX_TIME_UNTIL_EXPIRATION;
   result["VOILK_MAX_TRANSACTION_SIZE"] = VOILK_MAX_TRANSACTION_SIZE;
   result["VOILK_MAX_UNDO_HISTORY"] = VOILK_MAX_UNDO_HISTORY;
   result["VOILK_MAX_URL_LENGTH"] = VOILK_MAX_URL_LENGTH;
   result["VOILK_MAX_VOTE_CHANGES"] = VOILK_MAX_VOTE_CHANGES;
   result["VOILK_MAX_VOTED_WITNESSES_HF0"] = VOILK_MAX_VOTED_WITNESSES_HF0;
   result["VOILK_MAX_VOTED_WITNESSES_HF17"] = VOILK_MAX_VOTED_WITNESSES_HF17;
   result["VOILK_MAX_WITHDRAW_ROUTES"] = VOILK_MAX_WITHDRAW_ROUTES;
   result["VOILK_MAX_WITNESS_URL_LENGTH"] = VOILK_MAX_WITNESS_URL_LENGTH;
   result["VOILK_MIN_ACCOUNT_CREATION_FEE"] = VOILK_MIN_ACCOUNT_CREATION_FEE;
   result["VOILK_MIN_ACCOUNT_NAME_LENGTH"] = VOILK_MIN_ACCOUNT_NAME_LENGTH;
   result["VOILK_MIN_BLOCK_SIZE_LIMIT"] = VOILK_MIN_BLOCK_SIZE_LIMIT;
   result["VOILK_MIN_BLOCK_SIZE"] = VOILK_MIN_BLOCK_SIZE;
   result["VOILK_MIN_CONTENT_REWARD"] = VOILK_MIN_CONTENT_REWARD;
   result["VOILK_MIN_CURATE_REWARD"] = VOILK_MIN_CURATE_REWARD;
   result["VOILK_MIN_PERMLINK_LENGTH"] = VOILK_MIN_PERMLINK_LENGTH;
   result["VOILK_MIN_REPLY_INTERVAL"] = VOILK_MIN_REPLY_INTERVAL;
   result["VOILK_MIN_REPLY_INTERVAL_HF20"] = VOILK_MIN_REPLY_INTERVAL_HF20;
   result["VOILK_MIN_ROOT_COMMENT_INTERVAL"] = VOILK_MIN_ROOT_COMMENT_INTERVAL;
   result["VOILK_MIN_VOTE_INTERVAL_SEC"] = VOILK_MIN_VOTE_INTERVAL_SEC;
   result["VOILK_MINER_ACCOUNT"] = VOILK_MINER_ACCOUNT;
   result["VOILK_MINER_PAY_PERCENT"] = VOILK_MINER_PAY_PERCENT;
   result["VOILK_MIN_FEEDS"] = VOILK_MIN_FEEDS;
   result["VOILK_MINING_REWARD"] = VOILK_MINING_REWARD;
   result["VOILK_MINING_TIME"] = VOILK_MINING_TIME;
   result["VOILK_MIN_LIQUIDITY_REWARD"] = VOILK_MIN_LIQUIDITY_REWARD;
   result["VOILK_MIN_LIQUIDITY_REWARD_PERIOD_SEC"] = VOILK_MIN_LIQUIDITY_REWARD_PERIOD_SEC;
   result["VOILK_MIN_PAYOUT_VSD"] = VOILK_MIN_PAYOUT_VSD;
   result["VOILK_MIN_POW_REWARD"] = VOILK_MIN_POW_REWARD;
   result["VOILK_MIN_PRODUCER_REWARD"] = VOILK_MIN_PRODUCER_REWARD;
   result["VOILK_MIN_TRANSACTION_EXPIRATION_LIMIT"] = VOILK_MIN_TRANSACTION_EXPIRATION_LIMIT;
   result["VOILK_MIN_TRANSACTION_SIZE_LIMIT"] = VOILK_MIN_TRANSACTION_SIZE_LIMIT;
   result["VOILK_MIN_UNDO_HISTORY"] = VOILK_MIN_UNDO_HISTORY;
   result["VOILK_NULL_ACCOUNT"] = VOILK_NULL_ACCOUNT;
   result["VOILK_NUM_INIT_MINERS"] = VOILK_NUM_INIT_MINERS;
   result["VOILK_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM"] = VOILK_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM;
   result["VOILK_OWNER_AUTH_RECOVERY_PERIOD"] = VOILK_OWNER_AUTH_RECOVERY_PERIOD;
   result["VOILK_OWNER_CHALLENGE_COOLDOWN"] = VOILK_OWNER_CHALLENGE_COOLDOWN;
   result["VOILK_OWNER_CHALLENGE_FEE"] = VOILK_OWNER_CHALLENGE_FEE;
   result["VOILK_OWNER_UPDATE_LIMIT"] = VOILK_OWNER_UPDATE_LIMIT;
   result["VOILK_POST_AVERAGE_WINDOW"] = VOILK_POST_AVERAGE_WINDOW;
   result["VOILK_POST_REWARD_FUND_NAME"] = VOILK_POST_REWARD_FUND_NAME;
   result["VOILK_POST_WEIGHT_CONSTANT"] = VOILK_POST_WEIGHT_CONSTANT;
   result["VOILK_POW_APR_PERCENT"] = VOILK_POW_APR_PERCENT;
   result["VOILK_PRODUCER_APR_PERCENT"] = VOILK_PRODUCER_APR_PERCENT;
   result["VOILK_PROXY_TO_SELF_ACCOUNT"] = VOILK_PROXY_TO_SELF_ACCOUNT;
   result["VOILK_VSD_INTEREST_COMPOUND_INTERVAL_SEC"] = VOILK_VSD_INTEREST_COMPOUND_INTERVAL_SEC;
   result["VOILK_SECONDS_PER_YEAR"] = VOILK_SECONDS_PER_YEAR;
   result["VOILK_RECENT_RSHARES_DECAY_TIME_HF19"] = VOILK_RECENT_RSHARES_DECAY_TIME_HF19;
   result["VOILK_RECENT_RSHARES_DECAY_TIME_HF17"] = VOILK_RECENT_RSHARES_DECAY_TIME_HF17;
   result["VOILK_REVERSE_AUCTION_WINDOW_SECONDS_HF6"] = VOILK_REVERSE_AUCTION_WINDOW_SECONDS_HF6;
   result["VOILK_REVERSE_AUCTION_WINDOW_SECONDS_HF20"] = VOILK_REVERSE_AUCTION_WINDOW_SECONDS_HF20;
   result["VOILK_ROOT_POST_PARENT"] = VOILK_ROOT_POST_PARENT;
   result["VOILK_SAVINGS_WITHDRAW_REQUEST_LIMIT"] = VOILK_SAVINGS_WITHDRAW_REQUEST_LIMIT;
   result["VOILK_SAVINGS_WITHDRAW_TIME"] = VOILK_SAVINGS_WITHDRAW_TIME;
   result["VOILK_VSD_START_PERCENT_HF14"] = VOILK_VSD_START_PERCENT_HF14;
   result["VOILK_VSD_START_PERCENT_HF20"] = VOILK_VSD_START_PERCENT_HF20;
   result["VOILK_VSD_STOP_PERCENT_HF14"] = VOILK_VSD_STOP_PERCENT_HF14;
   result["VOILK_VSD_STOP_PERCENT_HF20"] = VOILK_VSD_STOP_PERCENT_HF20;
   result["VOILK_SECOND_CASHOUT_WINDOW"] = VOILK_SECOND_CASHOUT_WINDOW;
   result["VOILK_SOFT_MAX_COMMENT_DEPTH"] = VOILK_SOFT_MAX_COMMENT_DEPTH;
   result["VOILK_START_MINER_VOTING_BLOCK"] = VOILK_START_MINER_VOTING_BLOCK;
   result["VOILK_START_COINING_BLOCK"] = VOILK_START_COINING_BLOCK;
   result["VOILK_TEMP_ACCOUNT"] = VOILK_TEMP_ACCOUNT;
   result["VOILK_UPVOTE_LOCKOUT_HF7"] = VOILK_UPVOTE_LOCKOUT_HF7;
   result["VOILK_UPVOTE_LOCKOUT_HF17"] = VOILK_UPVOTE_LOCKOUT_HF17;
   result["VOILK_UPVOTE_LOCKOUT_SECONDS"] = VOILK_UPVOTE_LOCKOUT_SECONDS;
   result["VOILK_COINING_FUND_PERCENT"] = VOILK_COINING_FUND_PERCENT;
   result["VOILK_COINING_WITHDRAW_INTERVALS"] = VOILK_COINING_WITHDRAW_INTERVALS;
   result["VOILK_COINING_WITHDRAW_INTERVALS_PRE_HF_16"] = VOILK_COINING_WITHDRAW_INTERVALS_PRE_HF_16;
   result["VOILK_COINING_WITHDRAW_INTERVAL_SECONDS"] = VOILK_COINING_WITHDRAW_INTERVAL_SECONDS;
   result["VOILK_VOTE_DUST_THRESHOLD"] = VOILK_VOTE_DUST_THRESHOLD;
   result["VOILK_VOTING_MANA_REGENERATION_SECONDS"] = VOILK_VOTING_MANA_REGENERATION_SECONDS;
   result["VOILK_SYMBOL"] = VOILK_SYMBOL;
   result["COINS_SYMBOL"] = COINS_SYMBOL;
   result["VOILK_VIRTUAL_SCHEDULE_LAP_LENGTH"] = VOILK_VIRTUAL_SCHEDULE_LAP_LENGTH;
   result["VOILK_VIRTUAL_SCHEDULE_LAP_LENGTH2"] = VOILK_VIRTUAL_SCHEDULE_LAP_LENGTH2;
   result["VOILK_MAX_LIMIT_ORDER_EXPIRATION"] = VOILK_MAX_LIMIT_ORDER_EXPIRATION;
   result["VOILK_DELEGATION_RETURN_PERIOD_HF0"] = VOILK_DELEGATION_RETURN_PERIOD_HF0;
   result["VOILK_DELEGATION_RETURN_PERIOD_HF20"] = VOILK_DELEGATION_RETURN_PERIOD_HF20;
   result["VOILK_RD_MIN_DECAY_BITS"] = VOILK_RD_MIN_DECAY_BITS;
   result["VOILK_RD_MAX_DECAY_BITS"] = VOILK_RD_MAX_DECAY_BITS;
   result["VOILK_RD_DECAY_DENOM_SHIFT"] = VOILK_RD_DECAY_DENOM_SHIFT;
   result["VOILK_RD_MAX_POOL_BITS"] = VOILK_RD_MAX_POOL_BITS;
   result["VOILK_RD_MAX_BUDGET_1"] = VOILK_RD_MAX_BUDGET_1;
   result["VOILK_RD_MAX_BUDGET_2"] = VOILK_RD_MAX_BUDGET_2;
   result["VOILK_RD_MAX_BUDGET_3"] = VOILK_RD_MAX_BUDGET_3;
   result["VOILK_RD_MAX_BUDGET"] = VOILK_RD_MAX_BUDGET;
   result["VOILK_RD_MIN_DECAY"] = VOILK_RD_MIN_DECAY;
   result["VOILK_RD_MIN_BUDGET"] = VOILK_RD_MIN_BUDGET;
   result["VOILK_RD_MAX_DECAY"] = VOILK_RD_MAX_DECAY;
   result["VOILK_ACCOUNT_SUBSIDY_PRECISION"] = VOILK_ACCOUNT_SUBSIDY_PRECISION;
   result["VOILK_WITNESS_SUBSIDY_BUDGET_PERCENT"] = VOILK_WITNESS_SUBSIDY_BUDGET_PERCENT;
   result["VOILK_WITNESS_SUBSIDY_DECAY_PERCENT"] = VOILK_WITNESS_SUBSIDY_DECAY_PERCENT;
   result["VOILK_DEFAULT_ACCOUNT_SUBSIDY_DECAY"] = VOILK_DEFAULT_ACCOUNT_SUBSIDY_DECAY;
   result["VOILK_DEFAULT_ACCOUNT_SUBSIDY_BUDGET"] = VOILK_DEFAULT_ACCOUNT_SUBSIDY_BUDGET;
   result["VOILK_DECAY_BACKSTOP_PERCENT"] = VOILK_DECAY_BACKSTOP_PERCENT;

   return result;
}

} } // voilk::protocol
